### ISSUE TITLE
The migration is completed, but temporary tables and triggers are not created.

### ISSUE THREAD

**Issue by J1STAR** [Shopify/lhm#139]
When I used soundcloud/lhm, I checked that temporary tables and triggers were created,
but when I used that fork, temporary tables and triggers were not created.

### Migration
![image](https://user-images.githubusercontent.com/8870540/220069359-4ad78d1f-0aea-4b22-a149-3a4f35efd35a.png)

### In Progress
![image](https://user-images.githubusercontent.com/8870540/220070530-93c4ca19-1bc2-4325-a68d-f76e93363d40.png)

### After
![image](https://user-images.githubusercontent.com/8870540/220070597-14157d2f-b280-4468-aacf-2cdbe588c25d.png)

Is there anything I missed?
I need your help.

**Comment by dgavey** [comment]
I commented out this line in my local copy of the gem so I could test fully in development environment 
https://github.com/Shopify/lhm/blob/master/lib/lhm/railtie.rb#L5
