### ISSUE TITLE
LHM 4.2.1 and 4.2.2 released to rubygems, but not github releases?

### ISSUE THREAD

**Issue by broksonic21** [Shopify/lhm#162]
https://rubygems.org/gems/lhm-shopify/versions has 4.2.1 and 4.2.2 (and Dependabot picked them up), but they:

* aren't listed here: https://github.com/Shopify/lhm/releases

Is the releases in github still supported?

**Comment by coding-chimp** [comment]
Sorry, we forgot to create them. I've created them now.
