### ISSUE TITLE
Rubygems support?

### ISSUE THREAD

**Issue by hakusaro** [Shopify/lhm#79]
Heya! I was wondering if we could get a tiny bit more open source support on this project. LHM is really great, and I really love the fact that Shopify forked it. But I think that you should go one step further and throw this on Rubygems, rather than keeping it on an internal package store.

I know there's a certain level of support implied by doing this, and I'm sorry about asking for that kind of commitment. However, you could throw a disclaimer up and warn people about any lack of support or reiterate the BSD license to mitigate that.

It's kind of troublesome to pin to this repo and use commit shas to reference it, for obvious reasons. If you're not down for Rubygems, maybe the new github package store service would be palatable?

Thanks! ❤️

**Comment by feliperaul** [comment]
I'd also like to thank the Shopify team for keeping this fork. You guys rock!

**Comment by hakusaro** [comment]
I agree completely! I really love Shopify for maintaining this gem! 💖

GitHub <notifications@github.com> wrote:
“

I'd also like to thank the Shopify team for keeping this fork. You guys rock!

**Comment by epugh** [comment]
I'm commenting on this as well, wish that adding `gem 'lhm'` pulled this fork in, or you updated readme to be more specific!

**Comment by epugh** [comment]
I wanted to follow up on this.  I see that a release `v3.3.3` was made, however I also found this gem that might have been a release as well?  https://rubygems.org/gems/shopify_lhm/versions/9001.0 was released Sept 15th, which doesn't quite match to either of the most recent releases on this repo.

I want to use it, but the page on rubygems is kind of bare, so I'm nervous about just grabbing it!

**Comment by hakusaro** [comment]
It's just a placeholder: https://my.diffend.io/gems/shopify_lhm/9001.0

I suggest using lhm by adding this repo as a git dependency. It works okay, and dependabot and other services can read it fine.

**Comment by allisonphillips** [comment]
See https://rubygems.org/gems/lhm-shopify

**Comment by driv3r** [comment]
Package is up so closing :)
