### ISSUE TITLE
NOT NULL is not kept when renaming a column

### ISSUE THREAD

**Issue by dwdking** [Shopify/lhm#97]
The NOT NULL property of a column is not kept when using rename_column.

I believe this is caused by [line 87](https://github.com/Shopify/lhm/blob/ea0e538891486fccca94eadc5ed5ea272eb308f4/lib/lhm/migrator.rb#L87) in lib/lhm/migrator.rb and it using `unless col[:is_nullable]` and `col[:is_nullable]` return a value of 'YES'/'NO' instead of a boolean.

**Comment by shuhaowu** [comment]
Might want to release a new version as well.
